package org.example.timetable.entities;

public enum WarningType {
    CONFLICT,  // DO NOT RENAME ANY OF THESE VARIABLES
    CRQ,  // DO NOT RENAME ANY OF THESE VARIABLES
    EXC,  // DO NOT RENAME ANY OF THESE VARIABLES
    PRQ,  // DO NOT RENAME ANY OF THESE VARIABLES
    DIST,  // DO NOT RENAME ANY OF THESE VARIABLES
    FYF,  // DO NOT RENAME ANY OF THESE VARIABLES
    UNKNOWN,  // DO NOT RENAME ANY OF THESE VARIABLES,
    TAKEN,
    MISSING_LEC,
    MISSING_TUT,
    MISSING_PRA
}
