postId = "TBA"
postCode = "TBA"
postName = "TBA"
subjectId = "TBA"
subjectCode = "TBA"
subjectName = "TBA"
designationId = "TBA"
designationCode = "TBA"
designationName = "TBA"
yearOfStudy = "TBA"
typeOfProgramId = "TBA"
typeOfProgramCode = "TBA"
typeOfProgramName = "TBA"
primaryOrgId = "TBA"
primaryOrgCode = "TBA"
primaryOrgName = "TBA"
secondaryOrgId = "TBA"
secondaryOrgCode = "TBA"
secondaryOrgName = "TBA"
assocOrgId = "TBA"
assocOrgCode = "TBA"
assocOrgName = "TBA"
adminOrgId = "TBA"
adminOrgCode = "TBA"
adminOrgName = "TBA"
restrictedGroup = "TBA"



def is_null(item_to_check) -> bool:
    return item_to_check is None
